#!/bin/bash

echo "Updater Script V2.0"
echo "by javelinanddart"

echo "Welcome $USER, this is my update script."
echo "It will help keep your system up-to-date"

echo "Are you ready?"
read -p "Press [Enter] to continue or [CTRL+C] to abort"

echo "Updating Package List"
sudo apt-get update > ~/UpdateLog
echo "Done"
echo "Upgrading Standard Packages"
sudo apt-get upgrade -y >> ~/UpdateLog
echo "Done"
echo "Upgrading Distribution and Kernel"
sudo apt-get dist-upgrade -y >> ~/UpdateLog
echo "Done"
exit
